services:
  zookeeper:
    image: zookeeper:latest
    ports:
     - "2181:2181"
  kafka:
    image: apache/kafka:latest
    ports:
     - "9092:9092"
    expose:
     - "9093"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093,OUTSIDE://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "topic_test:1:1"
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock 



# # Docker image kafka
docker run -p 9092:9092 --name kafka-server apache/kafka:3.7.0

# Set up kafka topic
docker exec -it kafka-server /opt/kafka/bin/kafka-topics.sh --create --topic delhaize-shop --bootstrap-server localhost:9092

# check if file is created
docker exec kafka kafka-topics.sh --list --bootstrap-server localhost:9092

docker exec -it kafka-server /opt/kafka/bin/kafka-topics.sh --describe --topic delhaize-shop --bootstrap-server localhost:9092